### ISSUE TITLE
Error in submission. Try again. 

### ISSUE THREAD

**Issue by TADstudent** [sebastianstigler/testing_und_debugging_submit#2]
Submit Befehlt funktioniert nicht. Folgende Fehlermeldung wird angezeigt:
Error in submission. Try again.
If the error persist, open a new issue at:
https://github.com/sebastianstigler/testing_und_debugging_submit/issues

Habe den submit ausgeführt und festgestellt, dass ich mein Passwort nicht mehr weiß. Nach der Passwortänderung erneut submit ausgeführt, Daten eingegeben und erhalte die obige Fehlermeldung.

Direkte Ausführung des gists Befehls(gists authorize -u username -c password) liefert:
Authentication token written in '~/.gistsrc'

Login auf der Website funktioniert problemlos.

**Comment by sebastianstigler** [comment]
Kopierens Sie wie besprochen die `~/.gistsrc` Datei von der ursprünglichen VM in die Neue.
